// src/components/Contact.tsx
import { useState } from 'react';
import ReCAPTCHA from 'react-google-recaptcha';

export default function Contact() {
    const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
    const [output, setOutput] = useState('');

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        // Your contact form submission logic here
    };

    return (
        <form className="contact" onSubmit={handleSubmit} aria-hidden="true">
            <input
                type="email"
                name="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="EMAIL"
                required
            />

            <textarea
                name="message"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="MESSAGE"
                required
            />
            
            <ReCAPTCHA
                sitekey="6Ldmpp4bAAAAAIn0pk_nXN03djoG7h5F_GAfOOyy"
                theme="dark"
                className="g-recaptcha"
            />

            <button id="my-form-button">Submit</button>
            <p>{output}</p>
        </form>
    );
}

// src/components/windows/contact.vue
<template>
  <Modal
    v-model="show"
    :fullscreen="false"
    name="contact"
    width="280px"
    @closed="clear"
  >
    <template v-slot:title>Contact me</template>
    <template v-slot:content>
      <form class="contact" @submit.prevent="contact" aria-hidden="true">
        <input
          type="email"
          name="email"
          v-model="email"
          placeholder="EMAIL"
          required
        />

        <textarea
          type="text"
          name="message"
          v-model="message"
          placeholder="MESSAGE"
          required
        />
        <div
          class="g-recaptcha"
          data-theme="dark"
          data-sitekey="6Ldmpp4bAAAAAIn0pk_nXN03djoG7h5F_GAfOOyy"
          required
        ></div>
        <button id="my-form-button">Submit</button>
        <p>{{ output }}</p>
      </form>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { ref } from "vue";

const show = ref(false);
const output = ref("");

const email = ref(""),
  message = ref("");

const endpoint = "https://formspree.io/f/xleawwng";
function contact(event: any) {
  let data = new FormData(event.target);
  fetch(endpoint, {
    method: "POST",
    body: data,
    headers: {
      Accept: "application/json",
    },
  })
    .then((response) => response.json())
    .then((data) => {
      output.value = data.ok
        ? "I will try to reply as soon as possible!"
        : data.error;

      if (data.ok) clear();
    })
    .catch(() => {
      output.value = "Oops! There was a problem submitting your form";
    });
}

function clear() {
  email.value = "";
  message.value = "";
}
</script>
