// src/components/windows/socials.vue
<template>
  <Modal v-model="show" :fullscreen="false" name="socials" width="280px">
    <template v-slot:title>Social Media</template>
    <template v-slot:content>
      <div
        v-for="item in socials"
        :key="item.name"
        class="space-between"
        style="width: none"
      >
        <div class="socials">
          <div v-if="item.name == 'br'" style="margin-bottom: 10px" />
          <div v-else>
            <img :src="images[item.name]" width="16" />
            <h4>{{ item.name }}</h4>
          </div>
        </div>
        <h4 class="socials">
          <strong>
            <a :href="item.href" aria-hidden="true" target="_blank">{{
              item.text || ""
            }}</a>
          </strong>
        </h4>
      </div>
    </template>
  </Modal>
</template>

<script setup lang="ts">
import { ref } from "vue";

import socials from "../../assets/windows/socials.json";

const show = ref(false);

let images: any = {};
for (let social of socials) {
  if (social.name == "br") continue;

  let image: any = new URL(
    `../../assets/images/${social.name}.png`,
    import.meta.url
  );

  images[social.name] = image;
}
</script>

// src/windows/socials.tsx
import Modal from "../components/Modal";
import socials from "../assets/windows/socials.json";

let images: { [key: string]: string } = {};
for (let social of socials) {
    if (social.name == "br") continue;

    let image: any = new URL(
        `../assets/images/${social.name}.png`,
        import.meta.url
    );

    images[social.name] = image;
}
export default function Socials() {
    return (
        <Modal name="socials" title="Social Media" width="280px">
            {socials.map(item => (
                <div className="space-between" key={item.name}>
                    <div className="socials">
                        {item.name == "br"
                            ? <div style={{ marginBottom: "10px" }} />
                            : <div>
                                <img src={images[item.name]} width="16" />
                                <h4>{item.name}</h4>
                            </div>
                        }
                    </div>
                    <h4 className="socials">
                        <strong>
                            <a href={item.href} aria-hidden target="_blank">
                                {item.text || ""}
                            </a>
                        </strong>
                    </h4>
                </div>
            ))}
        </Modal>
    )
}
